import mongoose from 'mongoose';

const promotionSchema = new mongoose.Schema({
    // Promoted courses (maximum 3)
    courses: [{
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Course',
        required: true
    }],
    
    // Promotion period
    startDate: {
        type: Date,
        required: true,
        default: Date.now
    },
    
    endDate: {
        type: Date,
        required: true,
        default: function() {
            // Default to 1 week from start date
            const oneWeek = new Date();
            oneWeek.setDate(oneWeek.getDate() + 7);
            return oneWeek;
        }
    },
    
    // Promotion status
    status: {
        type: String,
        enum: ['active', 'expired', 'inactive'],
        default: 'active'
    },
    
    // Promotion type
    type: {
        type: String,
        enum: ['popular', 'featured', 'special'],
        default: 'popular'
    },
    
    // Auto-generated flag
    isAutoGenerated: {
        type: Boolean,
        default: true
    },
    
    // Promotion metrics
    views: {
        type: Number,
        default: 0
    },
    
    enrollments: {
        type: Number,
        default: 0
    }
}, {
    timestamps: true
});

// Index for better query performance
promotionSchema.index({ status: 1, endDate: 1 });
promotionSchema.index({ type: 1, status: 1 });

// Virtual to check if promotion is still valid
promotionSchema.virtual('isValid').get(function() {
    const now = new Date();
    return this.status === 'active' && 
           this.startDate <= now && 
           this.endDate > now;
});

// Static method to get current active promotions
promotionSchema.statics.getCurrentPromotions = function(type = 'popular') {
    const now = new Date();
    return this.findOne({
        type: type,
        status: 'active',
        startDate: { $lte: now },
        endDate: { $gt: now }
    }).populate({
        path: 'courses',
        populate: {
            path: 'coach',
            select: 'name email phone specialization bio experience image employmentType'
        }
    });
};

// Static method to create new popular courses promotion
promotionSchema.statics.createPopularPromotion = async function() {
    try {
        // Import Course model
        const Course = mongoose.model('Course');
        
        // Get all active courses
        const activeCourses = await Course.find({ status: 'active' });
        
        if (activeCourses.length === 0) {
            throw new Error('No active courses available for promotion');
        }
        
        // Randomly select up to 3 courses
        const shuffled = activeCourses.sort(() => 0.5 - Math.random());
        const selectedCourses = shuffled.slice(0, Math.min(3, activeCourses.length));
        
        // Expire any existing active popular promotions
        await this.updateMany(
            { type: 'popular', status: 'active' },
            { status: 'expired' }
        );
        
        // Create new promotion
        const promotion = new this({
            courses: selectedCourses.map(course => course._id),
            type: 'popular',
            status: 'active',
            isAutoGenerated: true
        });
        
        await promotion.save();
        return promotion;
        
    } catch (error) {
        console.error('Error creating popular promotion:', error);
        throw error;
    }
};

// Static method to refresh promotions if needed
promotionSchema.statics.refreshPromotionsIfNeeded = async function() {
    try {
        const currentPromotion = await this.getCurrentPromotions('popular');
        
        // If no active promotion or it's expired, create a new one
        if (!currentPromotion) {
            console.log('🎯 Creating new popular courses promotion...');
            return await this.createPopularPromotion();
        }
        
        return currentPromotion;
        
    } catch (error) {
        console.error('Error refreshing promotions:', error);
        throw error;
    }
};

// Pre-save middleware to validate course count
promotionSchema.pre('save', function(next) {
    if (this.courses.length > 3) {
        return next(new Error('Maximum 3 courses allowed per promotion'));
    }
    next();
});

// Method to increment views
promotionSchema.methods.incrementViews = function() {
    this.views += 1;
    return this.save();
};

// Method to increment enrollments
promotionSchema.methods.incrementEnrollments = function() {
    this.enrollments += 1;
    return this.save();
};

// Method to check if promotion should be expired
promotionSchema.methods.checkExpiry = function() {
    const now = new Date();
    if (this.endDate <= now && this.status === 'active') {
        this.status = 'expired';
        return this.save();
    }
    return Promise.resolve(this);
};

const Promotion = mongoose.model('Promotion', promotionSchema);

export default Promotion;